# Generated by Django 5.2 on 2025-04-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
